name: Extract IP Addresses

on:
  schedule:
    # 每三个小时运行一次
    - cron: "0 */3 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  extract-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow the job to write to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run Python script
        run: python extract_ip.py

      - name: Commit and push ip.txt to repository
        uses: ad-m/github-push-action@master # 使用现成的 action 来 push，更简单
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: false #如果遇到冲突，设置force为true。
          add: 'ip.txt'
