# .github/workflows/update_cloudflare_dns.yml

name: Update Cloudflare DNS with Fastest IPs

on:
  schedule:
    # for Shanghai time, which is UTC+8.
    - cron: '0 19 * * *' 
  workflow_dispatch: # Allows manual triggering

jobs:
  update-dns:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Only needs read if script isn't changing repo files
                     # If your script writes logs back to repo, then 'write'
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run DNS Update Script
        env:
          RAW_URL: ${{ secrets.RAW_URL }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          DOMAIN_MAP_JSON: ${{ secrets.DOMAIN_MAP_JSON }}
          TARGET_COUNTRIES_JSON: ${{ secrets.TARGET_COUNTRIES_JSON }}
        # Ensure this matches the filename of your Python script
        run: python pxy2cf.py
