name: Update Proxy PL_IPs

on:
  workflow_dispatch: # 允许手动触发工作流
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 运行

jobs:
  get_ip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 或者您需要的 Python 版本

      - name: Install requests
        run: pip install requests

      - name: Run script
        env:
          RAW_URL: ${{ secrets.RAW_URL }} # 从 secrets 中获取 raw_url
        run: python prxips.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add prxyip.txt
          git commit -m "Update prxyip.txt with Python script"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main
